# Generated by Django 4.0.1 on 2023-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
    ]
