# Generated by Django 4.0.3 on 2023-02-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_attendancereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.unit'),
        ),
    ]
