# Generated by Django 4.0.3 on 2023-02-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_attendancereport_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateField(),
        ),
    ]
